version: "1.0.{build}"

image: Visual Studio 2022

# Test against the latest version of this Node.js version
environment:
  nodejs_version: "16.13.0"

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: "{version}"
  package_version: "{version}"
  assembly_version: "{version}"
  file_version: "{version}"
  informational_version: "{version}"

pull_requests:
  do_not_increment_build_number: true

branches:
  only:
    - main
init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
install:
  # Install repo specific stuff here
    - ps: Install-Product node $env:nodejs_version
    - cmd: cd ./src/SandDance.InteractiveExtension.js/
    - npm ci 
    - cmd: cd ../.. 
    - cmd: cd ./src/nteract.InteractiveExtension.js/
    - npm ci 
    - cmd: cd ../.. 
before_build:
  - cmd: dotnet --version
  - cmd: dotnet restore dotnetInteractiveExtensions.sln --verbosity q
 
build_script:
  - cmd: cd ./src/SandDance.InteractiveExtension.js/
  - npm run compile 
  - cmd: cd ../.. 
  - cmd: cd ./src/nteract.InteractiveExtension.js/
  - npm run compile 
  - cmd: cd ../.. 
  - cmd: dotnet build dotnetInteractiveExtensions.sln -c Release
after_build:
  # For once the build has completed
  - cmd: dotnet pack dotnetInteractiveExtensions.sln -o packages -c Release
artifacts:
  - path: "packages/**/*.nupkg"
    name: NugetPacakges

clone_depth: 1
test_script:
  - cmd: dotnet test dotnetInteractiveExtensions.sln
deploy:
  - provider: NuGet
    api_key:
      secure: 2rVyhSP7VBev5AaKvwPSXGY3Jc0Vhx4DKyDuc1k6TxyE6E3joCACpxG+AFyFNN6h

    skip_symbols: false
    artifact: /.*(\.|\.s)nupkg/
    on:
      branch: main
